parameters: {}
environment:
  ENV: production
packages:
    - name: ai-agent
      shared: false
      environment: {
        DATABASE_URL: "${DATABASE_URL}",
        OPENAI_API_KEY: "${OPENAI_API_KEY}",
        STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      }
      parameters: {}
      annotations: {}
      functions:
        - name: create
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: retrieve
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: update
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: delete
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: list
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
