parameters: {}
environment:
  ENV: production
packages:
    - name: ai-agent
      shared: false
      environment: {
        DATABASE_URL: "${DATABASE_URL}"
      }
      parameters: {}
      annotations: {}
      functions:
        - name: run
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
