alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
functions:
- github:
    branch: main
    deploy_on_push: true
    repo: thefrisson/serverless-ai-agent-run
  name: serverless-ai-agents
  routes:
  - path: /
  source_dir: /
name: ai-agents